# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"\x16\n\x07Message\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x12\n\x10PublishConfirmed\"\x12\n\x10SubscribeRequest2\x86\x01\n\x0cRelayService\x12\x38\n\x07Publish\x12\x10.service.Message\x1a\x19.service.PublishConfirmed\"\x00\x12<\n\tSubscribe\x12\x19.service.SubscribeRequest\x1a\x10.service.Message\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=26
  _MESSAGE._serialized_end=48
  _PUBLISHCONFIRMED._serialized_start=50
  _PUBLISHCONFIRMED._serialized_end=68
  _SUBSCRIBEREQUEST._serialized_start=70
  _SUBSCRIBEREQUEST._serialized_end=88
  _RELAYSERVICE._serialized_start=91
  _RELAYSERVICE._serialized_end=225
# @@protoc_insertion_point(module_scope)
