# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Org.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tOrg.proto\x12\x0cNP.OrgClient\")\n\x03Org\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x14\n\x0cNumberPeople\x18\x02 \x01(\x05*\x1f\n\x05Topic\x12\x08\n\x04None\x10\x00\x12\x0c\n\x08OrgTopic\x10\x14\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Org_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOPIC._serialized_start=70
  _TOPIC._serialized_end=101
  _ORG._serialized_start=27
  _ORG._serialized_end=68
# @@protoc_insertion_point(module_scope)
